
export const SET_CONTACTS_DATA = 'SET_CONTACTS_DATA';
export const CHANGE_SELECTED_CONTACT = 'CHANGE_SELECTED_CONTACT';
export const SHOW_ADD_CONTACT_FORM = 'SHOW_ADD_CONTACT_FORM';
export const SHOW_EDIT_CONTACT_FORM = 'SHOW_EDIT_CONTACT_FORM';
export const SHOW_CONTACT_INFO = 'SHOW_CONTACT_INFO';
export const SET_TO_EDIT_DATA = 'SET_TO_EDIT_DATA';
export const ADD_CONTACT = 'ADD_CONTACT';
export const SAVE_CONTACT = 'SAVE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';



